### ISSUE TITLE
unable to make copy of lang schema 

### ISSUE THREAD

**Issue by AdamWorley** [dendronhq/schema-library#3]
When I try to copy down the [lang schema](https://raw.githubusercontent.com/dendronhq/schema-library/main/vault/lang.schema.yml) I get the following error message:
![image](https://user-images.githubusercontent.com/28906234/146990768-6cdf691a-f285-4498-89dd-66120861de86.png)

I can't see anything wrong with the formatting compared to the version in this repo so I don't think any auto-formatter has broken anything.
![image](https://user-images.githubusercontent.com/28906234/146991636-050ecb8d-5434-4228-8c57-0edc4f9d5f66.png)

**Comment by marukoRoburesu** [comment]
I created a pull request that fixes this default lang.schema.yml see changes below:
#4
